services:
  app_1:
    build:
      context: ./app_1
    container_name: app_1
    working_dir: /app
    command: ["python", "app.py"]
    volumes:
      - ./app_1:/app
      - app1_data:/app/data
    ports:
      - "5001:5000"

  app_2:
    build:
      context: ./app_2
    container_name: app_2
    working_dir: /app
    command: ["python", "app1.py"]
    volumes:
      - ./app_2:/app
      - app2_data:/app/data
    ports:
      - "5002:5000"

volumes:
  app1_data:
  app2_data:
